"""Generate a temporary PPO config file that overrides base hyperparameters.

Reads PPO params from the merged sub-phase config and writes a Python file
that:
  - Imports BasePPORunnerCfg from the original rsl_rl_ppo_cfg module
  - Overrides only learning_rate, entropy_coef, and other tunable fields
  - Is loaded by train.py via the ``--agent_cfg`` flag
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


def generate_ppo_override(
    ppo_params: dict[str, Any],
    default_ppo: dict[str, Any],
    output_path: str | Path,
) -> Path:
    """Generate a PPO override config file.

    Parameters
    ----------
    ppo_params : dict
        PPO overrides for this sub-phase (e.g. ``{"learning_rate": 1e-3, "entropy_coef": 0.01}``).
    default_ppo : dict
        Full default PPO config from the plan's ``defaults.ppo`` section.
    output_path : str or Path
        Where to write the generated file.

    Returns
    -------
    Path
        Absolute path to the generated file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Merge defaults with overrides — overrides take precedence
    merged = _deep_merge(default_ppo, ppo_params)

    algo = merged.get("algorithm", {})
    policy = merged.get("policy", {})

    # Extract values with fallbacks
    learning_rate = algo.get("learning_rate", 1.0e-3)
    entropy_coef = algo.get("entropy_coef", 0.01)
    num_learning_epochs = algo.get("num_learning_epochs", 5)
    num_mini_batches = algo.get("num_mini_batches", 4)
    num_steps_per_env = merged.get("num_steps_per_env", 24)
    save_interval = merged.get("save_interval", 100)
    empirical_normalization = merged.get("empirical_normalization", False)
    max_iterations = merged.get("max_iterations", 50000)

    # Policy architecture
    init_noise_std = policy.get("init_noise_std", 1.0)
    actor_hidden_dims = policy.get("actor_hidden_dims", [512, 256, 128])
    critic_hidden_dims = policy.get("critic_hidden_dims", [512, 256, 128])
    activation = policy.get("activation", "elu")

    # Algorithm params
    value_loss_coef = algo.get("value_loss_coef", 1.0)
    use_clipped_value_loss = algo.get("use_clipped_value_loss", True)
    clip_param = algo.get("clip_param", 0.2)
    schedule = algo.get("schedule", "adaptive")
    gamma = algo.get("gamma", 0.99)
    lam = algo.get("lam", 0.95)
    desired_kl = algo.get("desired_kl", 0.01)
    max_grad_norm = algo.get("max_grad_norm", 1.0)

    source = f'''"""Auto-generated PPO config override — DO NOT EDIT MANUALLY.

Generated by ppo_override.py from the training plan.
This file is loaded via --agent_cfg in train.py.
"""

from isaaclab.utils import configclass
from isaaclab_rl.rsl_rl import RslRlOnPolicyRunnerCfg, RslRlPpoActorCriticCfg, RslRlPpoAlgorithmCfg


@configclass
class PhasePPORunnerCfg(RslRlOnPolicyRunnerCfg):
    num_steps_per_env = {num_steps_per_env}
    max_iterations = {max_iterations}
    save_interval = {save_interval}
    experiment_name = ""  # same as task name
    empirical_normalization = {str(empirical_normalization)}
    policy = RslRlPpoActorCriticCfg(
        init_noise_std={init_noise_std},
        actor_hidden_dims={actor_hidden_dims!r},
        critic_hidden_dims={critic_hidden_dims!r},
        activation="{activation}",
    )
    algorithm = RslRlPpoAlgorithmCfg(
        value_loss_coef={value_loss_coef},
        use_clipped_value_loss={str(use_clipped_value_loss)},
        clip_param={clip_param},
        entropy_coef={entropy_coef},
        num_learning_epochs={num_learning_epochs},
        num_mini_batches={num_mini_batches},
        learning_rate={learning_rate},
        schedule="{schedule}",
        gamma={gamma},
        lam={lam},
        desired_kl={desired_kl},
        max_grad_norm={max_grad_norm},
    )
'''

    output_path.write_text(source, encoding="utf-8")
    logger.info("Generated PPO override: %s", output_path)
    return output_path.resolve()


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge *override* into *base* (override wins)."""
    result = dict(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result
